Collections:
- Name: oe_net
  Metadata:
    Training Data: TinyDOTA
    Training Techniques:
      - AdamW with Momentum
      - Weight Decay
    Training Resources: 1x NVIDIA RTX 4000 SFF Ada Generation
    Architecture:
      - ResNet
  Paper:
    URL: https://openaccess.thecvf.com/content/ICCV2021/papers/Xie_Oriented_R-CNN_for_Object_Detection_ICCV_2021_paper.pdf
    Title: 'OE-NET: Tiny Object Detection in High-Resolution Satellite Imagery using Context Enhancement, Wasserstein Distance, and Vector Mapping'
  README: configs/oriented_rcnn/README.md

Models:
  - Name: oriented_rcnn_r50_fpn_fp16_1x_dota_le90
    In Collection: oriented_rcnn
    Config: configs/oriented_rcnn/oriented_rcnn_r50_fpn_fp16_1x_dota_le90.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 75.63
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/oriented_rcnn/oriented_rcnn_r50_fpn_fp16_1x_dota_le90/oriented_rcnn_r50_fpn_fp16_1x_dota_le90-57c88621.pth

  - Name: oriented_rcnn_r50_fpn_1x_dota_le90
    In Collection: oriented_rcnn
    Config: configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 75.69
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90/oriented_rcnn_r50_fpn_1x_dota_le90-6d2b2ce0.pth
